# Generated by Django 4.1.5 on 2023-01-26 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 26, 5, 28, 16, 995436)),
        ),
    ]
