# Generated by Django 4.1.5 on 2023-01-26 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodolist', '0002_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 1, 26, 5, 57, 36, 916708)),
        ),
    ]
