# Generated by Django 4.1.5 on 2023-01-26 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodolist', '0003_alter_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 1, 26, 6, 0, 1, 857784), null=True),
        ),
    ]
