# Generated by Django 4.1.5 on 2023-01-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodolist', '0005_alter_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
