# Generated by Django 4.1.5 on 2023-01-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodolist', '0007_alter_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
